version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 80:3000
    volumes:
      - ./:/code
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin01
    ports:
      - 27017:27017
    volumes:
      - /tridata/data/:/data/db
      - /tridata/data/mongod.conf:/etc/mongod.conf
volumes:
 mongodb:




sudo docker exec -it node-mongodb_mongo_1 bash




mongo -u root -p admin01
show dbs  ##list all the databases
use library #3switch to database

##command to injet value
db.books.insert({"name":"lan books"})

db.books.find().pretty()



docker exec node-mongodb_mongo_1 sh -c 'mongodump -d library -u root -p admin01 --archive' > db.dump


# Where and how to store data.
storage:
  dbPath: /var/lib/mongodb
  journal:
    enabled: true
#  engine:
#  mmapv1:
#  wiredTiger:

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

# network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1


# how the process runs
processManagement:
  timeZoneInfo: /usr/share/zoneinfo

#security:

#operationProfiling:

#replication:

#sharding:

## Enterprise-Only Options:

#auditLog:

#snmp: