wordpress:
    image: wordpress
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=Dygy!)p)3jS#N^Yp7cCm
    ports:
     - "80:80"
    volumes:
     - ./wp_data/html:/var/www/html
     - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=Dygy!)p)3jS#N^Yp7cCm
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./mariadb_database:/var/lib/mysql



uploads.ini 

file_uploads = On
memory_limit = 500M
upload_max_filesize = 500M
post_max_size = 500M
max_execution_time = 600
